# Generated by Django 4.2.5 on 2023-09-20 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.ImageField(default='profilepic\\profile.jpg', upload_to='profilepic/')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('district', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('edubackground', models.CharField(choices=[('1', 'Higher Secondary'), ('2', 'Diploma or Certificate Programs'), ('3', "Bachelor's Degree"), ('4', "Master's Degree"), ('5', 'Doctoral Degree (Ph.D.)')], default='1', max_length=30, null=True)),
                ('teachexp', models.IntegerField(default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
