# Generated by Django 4.2.5 on 2023-09-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[(0, '--------'), ('1', 'HTML'), ('2', 'CSS'), ('3', 'JavaScript'), ('4', 'Python'), ('5', 'Data Analysis'), ('6', 'Data Structure and Algorithms'), ('7', 'Natural Language Processing'), ('8', 'Machine Learning')], max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseImage',
            field=models.ImageField(upload_to='courseImage'),
        ),
    ]
