# Generated by Django 4.2.5 on 2023-09-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_slug_alter_course_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseTitle',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
