# Generated by Django 4.2.5 on 2023-09-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseTitle',
            field=models.CharField(max_length=100),
        ),
    ]
